version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8050:8050"
    command: python api.py

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data

networks:
  default:
    name: door-access-network